var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

export function generate() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

let quoteList = [
  "I am the one who knocks.",
  "Say my name.",
  "I did it for me. I liked it. I was good at it.",
  "Yeah, science!",
  "I'm in the empire business.",
  "I'm Batman.",
  "It's not who I am underneath, but what I do that defines me.",
  "Why do we fall? So we can learn to pick ourselves up.",
  "Sometimes the truth isn't good enough, sometimes people deserve more. Sometimes people deserve to have their faith rewarded.",
  "I am vengeance, I am the night, I am Batman!",
  "You know what they say: the bigger the smile, the sharper the knife.",
  "I'm not the hero you're looking for.",
  "We're superheroes. What the heck do we have to be scared of?",
  "People love that cozy feeling of the status quo. But it's a world where the powerful go unpunished.",
  "You think you can diabolically market your way out of this mess?",
  "The game is on.",
  "I'm not a psychopath, I'm a high-functioning sociopath. Do your research.",
  "When you have eliminated the impossible, whatever remains, however improbable, must be the truth.",
  "I may be on the side of the angels, but don't think for one second that I am one of them.",
  "Don't make people into heroes, John. Heroes don't exist, and if they did, I wouldn't be one of them.",
  "Time is a flat circle.",
  "The hubris it must take to yank a soul out of nonexistence, into this, meat. And to force a life into this, thresher.",
  "The only thing I knew for sure was that I wanted to be alone. I didn't care what it was for, whether it was just to be away from the world, or to be closer to something else.",
  "People incapable of guilt usually do have a good time.",
  "My life's been a circle of violence and degradation as long as I can remember. I'm ready to tie it off.",
];

export function generateQuotes() {
  return quoteList[Math.floor(Math.random() * quoteList.length)];
}
